#include<stdio.h>
#include<stdlib.h>

int main(){
    char sigma = '\x1';
    printf("La constante sigma es igual a: %c\n\n\n",sigma);
    char sigma2 = '\x2';
    printf("La constante sigma2 es igual a: %c\n\n\n",sigma2);
    char sigma3 = '\x03';
    printf("La constante sigma3 es igual a: %c\n\n\n",sigma3);
    char sigma4 = '\x04';
    printf("La constante sigma4 es igual a: %c\n\n\n",sigma4);
    char sigma5 = '\x05';
    printf("La constante sigma5 es igual a: %c\n\n\n",sigma5);
    char sigma6 = '\x06';
    printf("La constante sigma6 es igual a: %c\n\n\n",sigma6);
    char sigma7 = '\x07';
    printf("La constante sigma7 es igual a: %c\n\n\n",sigma7);
    char sigma8 = '\x08';
    printf("La constante sigma8 es igual a: %c\n\n\n",sigma8);
    char sigma9 = '\x09';
    printf("La constante sigma9 es igual a: %c\n\n\n",sigma9);
    char a = '\xA';
    printf("La constante a es igual a: %c\n\n\n",a);
    char a1 = '\xB';
    printf("La constante a1 es igual a: %c\n\n\n",a1);
    char a2 = '\xC';
    printf("La constante a2 es igual a: %c\n\n\n",a2);
    char a3 = '\xD';
    printf("La constante a3 es igual a: %c\n\n\n",a3);
    char a4 = '\xD';
    printf("La constante a4 es igual a: %c\n\n\n",a4);
    char a5 = '\xE';
    printf("La constante a5 es igual a: %c\n\n\n",a5);
    char a6 = '\xF';
    printf("La constante a6 es igual a: %c\n\n\n",a6);
    char b = '\x10';
    printf("La constante b es igual a: %c\n\n\n",b);
    char b1 = '\x11';
    printf("La constante b1 es igual a: %c\n\n\n",b1);
    char b2 = '\x12';
    printf("La constante b2 es igual a: %c\n\n\n",b2);
    char b3 = '\x13';
    printf("La constante b3 es igual a: %c\n\n\n",b3);
    char b4 = '\x14';
    printf("La constante b4 es igual a: %c\n\n\n",b4);
    char b5 = '\x15';
    printf("La constante b5 es igual a: %c\n\n\n",b5);
    char b6 = '\x16';
    printf("La constante b6 es igual a: %c\n\n\n",b6);
    char b7 = '\x17';
    printf("La constante b7 es igual a: %c\n\n\n",b7);
    char b8 = '\x18';
    printf("La constante b8 es igual a: %c\n\n\n",b8);
    char b9 = '\x19';
    printf("La constante b9 es igual a: %c\n\n\n",b9);
    char c = '\x1A';
    printf("La constante c es igual a: %c\n\n\n",c);
    char c1 = '\x1B';
    printf("La constante c1 es igual a: %c\n\n\n",c1);
    char c2 = '\x1C';
    printf("La constante c2 es igual a: %c\n\n\n",c2);
    char c3 = '\x1D';
    printf("La constante c3 es igual a: %c\n\n\n",c3);
    char c4  = '\x1E';
    printf("La constante c4 es igual a: %c\n\n\n",c4);
    char c5 = '\x1F';
    printf("La constante c5 es igual a: %c\n\n\n",c5);
    char d = '\x20';
    printf("La constante d es igual a: %c\n\n\n",d);
    char d1 = '\x21';
    printf("La constante d1 es igual a: %c\n\n\n",d1);
    char d2 = '\x22';
    printf("La constante d2 es igual a: %c\n\n\n",d2);
    char d3 = '\x23';
    printf("La constante d3 es igual a: %c\n\n\n",d3);
    char d4 = '\x24';
    printf("La constante d4 es igual a: %c\n\n\n",d4);
    char d5 = '\x25';
    printf("La constante d5 es igual a: %c\n\n\n",d5);
    char d6 = '\x26';
    printf("La constante d6 es igual a: %c\n\n\n",d6);
    char d7 = '\x27';
    printf("La constante d7 es igual a: %c\n\n\n",d7);
    char d8 = '\x28';
    printf("La constante d8 es igual a: %c\n\n\n",d8);
    char d9 = '\x29';
    printf("La constante d es igual a: %c\n\n\n",d9);
    char e = '\x2A';
    printf("La constante e es igual a: %c\n\n\n",e);
    char e1 = '\x2B';
    printf("La constante e1 es igual a: %c\n\n\n",e1);
    char e2 = '\x2C';
    printf("La constante e2 es igual a: %c\n\n\n",e2);
    char e3 = '\x2D';
    printf("La constante e3 es igual a: %c\n\n\n",e3);
    char e4 = '\x2E';
    printf("La constante e4 es igual a: %c\n\n\n",e4);
    char e5 = '\x2F';
    printf("La constante e5 es igual a: %c\n\n\n",e5);
    char f = '\x30';
    printf("La constante f es igual a: %c\n\n\n",f);
    char f1 = '\x31';
    printf("La constante f1 es igual a: %c\n\n\n",f1);
    char f2 = '\x32';
    printf("La constante f2 es igual a: %c\n\n\n",f2);
    char f3 = '\x33';
    printf("La constante f3 es igual a: %c\n\n\n",f3);
    char f4 = '\x34';
    printf("La constante f4 es igual a: %c\n\n\n",f4);
    char f5 = '\x35';
    printf("La constante f5 es igual a: %c\n\n\n",f5);
    char f6= '\x36';
    printf("La constante f6 es igual a: %c\n\n\n",f6);
    char f7 = '\x37';
    printf("La constante f7 es igual a: %c\n\n\n",f7);
    char f8 = '\x38';
    printf("La constante f8 es igual a: %c\n\n\n",f8);
    char f9 = '\x39';
    printf("La constante f9 es igual a: %c\n\n\n",f9);
    char g = '\x3A';
    printf("La constante g es igual a: %c\n\n\n",g);
    char g1 = '\x3B';
    printf("La constante g1 es igual a: %c\n\n\n",g1);
    char g2 = '\x3C';
    printf("La constante g2 es igual a: %c\n\n\n",g2);
    char g3 = '\x3D';
    printf("La constante g3 es igual a: %c\n\n\n",g3);
    char g4 = '\x3E';
    printf("La constante g4 es igual a: %c\n\n\n",g4);
    char g5 = '\x3F';
    printf("La constante g5 es igual a: %c\n\n\n",g5);
    char h = '\x40';
    printf("La constante h es igual a: %c\n\n\n",h);
    char h1 = '\x41';
    printf("La constante h1 es igual a: %c\n\n\n",h1);
    char h2 = '\x42';
    printf("La constante h2 es igual a: %c\n\n\n",h2);
    char h3 = '\x43';
    printf("La constante h3 es igual a: %c\n\n\n",h3);
    char h4 = '\x44';
    printf("La constante h4 es igual a: %c\n\n\n",h4);
    char h5 = '\x45';
    printf("La constante h5 es igual a: %c\n\n\n",h5);
    char h6 = '\x46';
    printf("La constante h6 es igual a: %c\n\n\n",h6);
    char h7 = '\x47';
    printf("La constante h7 es igual a: %c\n\n\n",h7);
    char h8 = '\x48';
    printf("La constante h8 es igual a: %c\n\n\n",h8);
    char h9 = '\x49';
    printf("La constante h9 es igual a: %c\n\n\n",h9);
    char i = '\x4A';
    printf("La constante i es igual a: %c\n\n\n",i);
    char i1 = '\x4B';
    printf("La constante i1 es igual a: %c\n\n\n",i1);
    char i2 = '\x4C';
    printf("La constante i2 es igual a: %c\n\n\n",i2);
    char i3 = '\x4D';
    printf("La constante i3 es igual a: %c\n\n\n",i3);
    char i4 = '\x4E';
    printf("La constante i4 es igual a: %c\n\n\n",i4);
    char i5 = '\x4F';
    printf("La constante i5 es igual a: %c\n\n\n",i5);
    char j = '\x50';
    printf("La constante j es igual a: %c\n\n\n",j);
    char j1 = '\x51';
    printf("La constante j1 es igual a: %c\n\n\n",j1);
    char j2 = '\x52';
    printf("La constante j2 es igual a: %c\n\n\n",j2);
    char j3 = '\x53';
    printf("La constante j3 es igual a: %c\n\n\n",j3);
    char j4 = '\x54';
    printf("La constante j4 es igual a: %c\n\n\n",j4);
    char j5 = '\x55';
    printf("La constante j5 es igual a: %c\n\n\n",j5);
    char j6 = '\x56';
    printf("La constante j6 es igual a: %c\n\n\n",j6);
    char j7 = '\x57';
    printf("La constante j7 es igual a: %c\n\n\n",j7);
    char j8 = '\x58';
    printf("La constante j8 es igual a: %c\n\n\n",j8);
    char j9 = '\x59';
    printf("La constante j9 es igual a: %c\n\n\n",j9);
    char k = '\x5A';
    printf("La constante k es igual a: %c\n\n\n",k);
    char k1 = '\x5B';
    printf("La constante k1 es igual a: %c\n\n\n",k1);
    char k2 = '\x5C';
    printf("La constante k2 es igual a: %c\n\n\n",k2);
    char k3 = '\x5D';
    printf("La constante k3 es igual a: %c\n\n\n",k3);
    char k4 = '\x5E';
    printf("La constante k4 es igual a: %c\n\n\n",k4);
    char k5 = '\x5F';
    printf("La constante k5 es igual a: %c\n\n\n",k5);
    char l = '\x60';
    printf("La constante l es igual a: %c\n\n\n",l);
    char l1 = '\x61';
    printf("La constante l1 es igual a: %c\n\n\n",l1);
    char l2 = '\x62';
    printf("La constante l2 es igual a: %c\n\n\n",l2);
    char l3 = '\x63';
    printf("La constante l3 es igual a: %c\n\n\n",l3);
    char l4 = '\x64';
    printf("La constante l4 es igual a: %c\n\n\n",l4);
    char l5 = '\x65';
    printf("La constante l5 es igual a: %c\n\n\n",l5);
    char l6 = '\x66';
    printf("La constante l6 es igual a: %c\n\n\n",l6);
    char l7 = '\x67';
    printf("La constante l7 es igual a: %c\n\n\n",l7);
    char l8 = '\x68';
    printf("La constante l8 es igual a: %c\n\n\n",l8);
    char l9 = '\x69';
    printf("La constante l9 es igual a: %c\n\n\n",l9);
    char m = '\x6A';
    printf("La constante m es igual a: %c\n\n\n",m);
    char m1 = '\x6B';
    printf("La constante m1 es igual a: %c\n\n\n",m1);
    char m2 = '\x6C';
    printf("La constante m2 es igual a: %c\n\n\n",m2);
    char m3 = '\x6D';
    printf("La constante m3 es igual a: %c\n\n\n",m3);
    char m4 = '\x6E';
    printf("La constante m4 es igual a: %c\n\n\n",m4);
    char m5 = '\x6F';
    printf("La constante m5 es igual a: %c\n\n\n",m5);
    char n = '\x70';
    printf("La constante n es igual a: %c\n\n\n",n);
    char n1 = '\x71';
    printf("La constante n1 es igual a: %c\n\n\n",n1);
    char n2 = '\x72';
    printf("La constante n2 es igual a: %c\n\n\n",n2);
    char n3 = '\x73';
    printf("La constante n3 es igual a: %c\n\n\n",n3);
    char n4 = '\x74';
    printf("La constante n4 es igual a: %c\n\n\n",n4);
    char n5 = '\x75';
    printf("La constante n5 es igual a: %c\n\n\n",n5);
    char n6 = '\x76';
    printf("La constante n6 es igual a: %c\n\n\n",n6);
    char n7 = '\x77';
    printf("La constante n7 es igual a: %c\n\n\n",n7);
    char n8 = '\x78';
    printf("La constante n8 es igual a: %c\n\n\n",n8);
    char n9 = '\x79';
    printf("La constante n9 es igual a: %c\n\n\n",n9);
    char o = '\x7A';
    printf("La constante o es igual a: %c\n\n\n",o);
    char o1 = '\x7B';
    printf("La constante o1 es igual a: %c\n\n\n",o1);
    char o2 = '\x7C';
    printf("La constante o2 es igual a: %c\n\n\n",o2);
    char o3 = '\x7D';
    printf("La constante o3 es igual a: %c\n\n\n",o3);
    char o4 = '\x7E';
    printf("La constante o4 es igual a: %c\n\n\n",o4);
    char o5 = '\x7F';
    printf("La constante o5 es igual a: %c\n\n\n",o5);
    char p = '\x80';
    printf("La constante p es igual a: %c\n\n\n",p);
    char p1 = '\x81';
    printf("La constante p1 es igual a: %c\n\n\n",p1);
    char p2 = '\x82';
    printf("La constante p2 es igual a: %c\n\n\n",p2);
    char p3 = '\x83';
    printf("La constante p3 es igual a: %c\n\n\n",p3);
    char p4 = '\x84';
    printf("La constante p4 es igual a: %c\n\n\n",p4);
    char p5 = '\x85';
    printf("La constante p5 es igual a: %c\n\n\n",p5);
    char p6 = '\x86';
    printf("La constante p6 es igual a: %c\n\n\n",p6);
    char p7 = '\x87';
    printf("La constante p7 es igual a: %c\n\n\n",p7);
    char p8 = '\x88';
    printf("La constante p8 es igual a: %c\n\n\n",p8);
    char p9 = '\x89';
    printf("La constante p9 es igual a: %c\n\n\n",p9);
    char q = '\x8A';
    printf("La constante q es igual a: %c\n\n\n",q);
    char q1 = '\x8B';
    printf("La constante q1 es igual a: %c\n\n\n",q1);
    char q2 = '\x8C';
    printf("La constante q2 es igual a: %c\n\n\n",q2);
    char q3 = '\x8D';
    printf("La constante q3 es igual a: %c\n\n\n",q3);
    char q4 = '\x8E';
    printf("La constante q4 es igual a: %c\n\n\n",q4);
    char q5 = '\x8F';
    printf("La constante q5 es igual a: %c\n\n\n",q5);
    char r = '\x90';
    printf("La constante r es igual a: %c\n\n\n",r);
    char r1 = '\x91';
    printf("La constante r1 es igual a: %c\n\n\n",r1);
    char r2 = '\x92';
    printf("La constante r2 es igual a: %c\n\n\n",r2);
    char r3 = '\x93';
    printf("La constante r3 es igual a: %c\n\n\n",r3);
    char r4 = '\x94';
    printf("La constante r4 es igual a: %c\n\n\n",r4);
    char r5 = '\x95';
    printf("La constante r5 es igual a: %c\n\n\n",r5);
    char r6 = '\x96';
    printf("La constante r6 es igual a: %c\n\n\n",r6);
    char r7 = '\x97';
    printf("La constante r7 es igual a: %c\n\n\n",r7);
    char r8 = '\x98';
    printf("La constante r8 es igual a: %c\n\n\n",r8);
    char r9 = '\x99';
    printf("La constante r9 es igual a: %c\n\n\n",r9);
    char s = '\x9A';
    printf("La constante s es igual a: %c\n\n\n",s);
    char s1 = '\x9B';
    printf("La constante s1 es igual a: %c\n\n\n",s1);
    char s2 = '\x9C';
    printf("La constante s2 es igual a: %c\n\n\n",s2);
    char s3 = '\x9D';
    printf("La constante s3 es igual a: %c\n\n\n",s3);
    char s4 = '\x9E';
    printf("La constante s4 es igual a: %c\n\n\n",s4);
    char s5 = '\x9F';
    printf("La constante s5 es igual a: %c\n\n\n",s5);
    char t = '\xA1';
    printf("La constante t es igual a: %c\n\n\n",t);
    char t1 = '\xA2';
    printf("La constante t1 es igual a: %c\n\n\n",t1);
    char t2 = '\xA2';
    printf("La constante t2 es igual a: %c\n\n\n",t2);
    char t3 = '\xA3';
    printf("La constante t3 es igual a: %c\n\n\n",t3);
    char t4 = '\xA4';
    printf("La constante t4 es igual a: %c\n\n\n",t4);
    char t5 = '\xA5';
    printf("La constante t5 es igual a: %c\n\n\n",t5);
    char t6 = '\xA6';
    printf("La constante t6 es igual a: %c\n\n\n",t6);
    char t7 = '\xA7';
    printf("La constante t7 es igual a: %c\n\n\n",t7);
    char t8 = '\xA8';
    printf("La constante t8 es igual a: %c\n\n\n",t8);
    char t9 = '\xA9';
    printf("La constante t9 es igual a: %c\n\n\n",t9);
    char u = '\xAA';
    printf("La constante u es igual a: %c\n\n\n",u);
    char u1 = '\xAB';
    printf("La constante u1 es igual a: %c\n\n\n",u1);
    char u2 = '\xAC';
    printf("La constante u2 es igual a: %c\n\n\n",u2);
    char u3 = '\xAD';
    printf("La constante u3 es igual a: %c\n\n\n",u3);
    char u4 = '\xAE';
    printf("La constante u4 es igual a: %c\n\n\n",u4);
    char u5 = '\xAF';
    printf("La constante u5 es igual a: %c\n\n\n",u5);
    char v = '\xB0';
    printf("La constante v es igual a: %c\n\n\n",v);
    char v1 = '\xB1';
    printf("La constante v1 es igual a: %c\n\n\n",v1);
    char v2 = '\xB2';
    printf("La constante v2 es igual a: %c\n\n\n",v2);
    char v3 = '\xB3';
    printf("La constante v3 es igual a: %c\n\n\n",v3);
    char v4 = '\xB4';
    printf("La constante v4 es igual a: %c\n\n\n",v4);
    char v5 = '\xB5';
    printf("La constante v5 es igual a: %c\n\n\n",v5);
    char v6 = '\xB6';
    printf("La constante v6 es igual a: %c\n\n\n",v6);
    char v7 = '\xB7';
    printf("La constante v7 es igual a: %c\n\n\n",v7);
    char v8 = '\xB8';
    printf("La constante v8 es igual a: %c\n\n\n",v8);
    char v9 = '\xB9';
    printf("La constante v9 es igual a: %c\n\n\n",v9);
    char x = '\xBA';
    printf("La constante x es igual a: %c\n\n\n",x);
    char x1 = '\xBB';
    printf("La constante x1 es igual a: %c\n\n\n",x1);
    char x2 = '\xBC';
    printf("La constante x2 es igual a: %c\n\n\n",x2);
    char x3 = '\xBD';
    printf("La constante x3 es igual a: %c\n\n\n",x3);
    char x4 = '\xBE';
    printf("La constante x4 es igual a: %c\n\n\n",x4);
    char x5 = '\xBF';
    printf("La constante x5 es igual a: %c\n\n\n",x5);
    char y = '\xC0';
    printf("La constante y es igual a: %c\n\n\n",y);
    char y| = '\xC1';
    printf("La constante y1 es igual a: %c\n\n\n",y1);
    char y2 = '\xC2';
    printf("La constante y2 es igual a: %c\n\n\n",y2);
    char y3 = '\xC3';
    printf("La constante y3 es igual a: %c\n\n\n",y3);
    char y4 = '\xC4';
    printf("La constante y4 es igual a: %c\n\n\n",y4);
    char y5 = '\xC5';
    printf("La constante y5 es igual a: %c\n\n\n",y5);
    char y6 = '\xC6';
    printf("La constante y6 es igual a: %c\n\n\n",y6);
    char y7 = '\xC7';
    printf("La constante y7 es igual a: %c\n\n\n",y7);
    char y8 = '\xC8';
    printf("La constante y8 es igual a: %c\n\n\n",y8);
    char y9 = '\xC9';
    printf("La constante y9 es igual a: %c\n\n\n",y9);
    char z = '\xCA';
    printf("La constante z es igual a: %c\n\n\n",z);
    char z1 = '\xCB';
    printf("La constante z1 es igual a: %c\n\n\n",z1);
    char z2 = '\xCC';
    printf("La constante z2 es igual a: %c\n\n\n",z2);
    char z3 = '\xCD';
    printf("La constante z3 es igual a: %c\n\n\n",z3);
    char z4 = '\xCE';
    printf("La constante z4 es igual a: %c\n\n\n",z4);
    char z5 = '\xCF';
    printf("La constante z5 es igual a: %c\n\n\n",z5);
    char ab = '\xD0';
    printf("La constante ab es igual a: %c\n\n\n",ab);
    char ab1 = '\xD1';
    printf("La constante ab1 es igual a: %c\n\n\n",ab1);
    char ab2 = '\xD2';
    printf("La constante ab2 es igual a: %c\n\n\n",ab2);
    char ab3 = '\xD3';
    printf("La constante ab3 es igual a: %c\n\n\n",ab3);
    char ab4 = '\xD4';
    printf("La constante ab4 es igual a: %c\n\n\n",ab4);
    char ab5 = '\xD5';
    printf("La constante ab5 es igual a: %c\n\n\n",ab5);
    char ab6 = '\xD6';
    printf("La constante ab6 es igual a: %c\n\n\n",ab6);
    char ab7 = '\xD7';
    printf("La constante ab es igual a: %c\n\n\n",ab7);
    char ab8 = '\xD8';
    printf("La constante ab es igual a: %c\n\n\n",ab8);
    char ab9 = '\xD9';
    printf("La constante ab9 es igual a: %c\n\n\n",ab9);
    char bc = '\xDA';
    printf("La constante bc es igual a: %c\n\n\n",bc);
    char bc1 = '\xDB';
    printf("La constante bc1 es igual a: %c\n\n\n",bc1);
    char bc2 = '\xDC';
    printf("La constante bc2 es igual a: %c\n\n\n",bc2);
    char bc3 = '\xDD';
    printf("La constante bc3 es igual a: %c\n\n\n",bc3);
    char bc4 = '\xDE';
    printf("La constante bc4 es igual a: %c\n\n\n",bc4);
    char bc5 = '\xDF';
    printf("La constante bc5 es igual a: %c\n\n\n",bc5);
    char cd = '\xE0';
    printf("La constante cd es igual a: %c\n\n\n",cd);
    char cd1 = '\xE1';
    printf("La constante cd1 es igual a: %c\n\n\n",cd1);
    char cd2 = '\xE2';
    printf("La constante cd2 es igual a: %c\n\n\n",cd2);
    char cd3 = '\xE3';
    printf("La constante cd3 es igual a: %c\n\n\n",cd3);
    char cd4 = '\xE4';
    printf("La constante cd4 es igual a: %c\n\n\n",cd4);
    char cd5 = '\xE5';
    printf("La constante cd5 es igual a: %c\n\n\n",cd5);
    char cd6 = '\xE6';
    printf("La constante cd6 es igual a: %c\n\n\n",cd6);
    char cd7 = '\xE7';
    printf("La constante cd7 es igual a: %c\n\n\n",cd7);
    char cd8 = '\xE8';
    printf("La constante cd8 es igual a: %c\n\n\n",cd8);
    char cd9 = '\xE9';
    printf("La constante cd9 es igual a: %c\n\n\n",cd9);
    char de = '\xEA';
    printf("La constante de es igual a: %c\n\n\n",de);
    char de1 = '\xEB';
    printf("La constante de1 es igual a: %c\n\n\n",de1);
    char de2 = '\xEC';
    printf("La constante de2 es igual a: %c\n\n\n",de2);
    char de3 = '\xED';
    printf("La constante de3 es igual a: %c\n\n\n",de3);
    char de4 = '\xEE';
    printf("La constante de4 es igual a: %c\n\n\n",de4);
    char de5 = '\xEF';
    printf("La constante de5 es igual a: %c\n\n\n",de5);
    char ef = '\xF0';
    printf("La constante ef es igual a: %c\n\n\n",ef);
    char ef1 = '\xF1';
    printf("La constante ef1 es igual a: %c\n\n\n",ef1);
    char ef2 = '\xF2';
    printf("La constante ef2 es igual a: %c\n\n\n",ef2);
    char ef3 = '\xF3';
    printf("La constante ef3 es igual a: %c\n\n\n",ef3);
    char ef4 = '\xF4';
    printf("La constante ef4 es igual a: %c\n\n\n",ef4);
    char ef5 = '\xF5';
    printf("La constante ef5 es igual a: %c\n\n\n",ef5);
    char ef6 = '\xF6';
    printf("La constante ef6 es igual a: %c\n\n\n",ef6);
    char ef7 = '\xF7';
    printf("La constante ef7 es igual a: %c\n\n\n",ef7);
    char ef8 = '\xF8';
    printf("La constante ef es igual a: %c\n\n\n",ef8);
    char ef9 = '\xF9';
    printf("La constante ef es igual a: %c\n\n\n",ef9);
    char fg = '\xFA';
    printf("La constante fg es igual a: %c\n\n\n",fg);
    char fg1 = '\xFB';
    printf("La constante fg1 es igual a: %c\n\n\n",fg1);
    char fg2 = '\xFC';
    printf("La constante fg2 es igual a: %c\n\n\n",fg2);
    char fg3 = '\xFD';
    printf("La constante fg3 es igual a: %c\n\n\n",fg3);
    char fg4 = '\xFE';
    printf("La constante fg4 es igual a: %c\n\n\n",fg4);
    char fg5 = '\xFF';
    printf("La constante fg5 es igual a: %c\n\n\n",fg5);
    system("pause");
    return 0;
}
