# Generated by Django 2.2.4 on 2019-11-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcliente',
            name='cuenta',
            field=models.IntegerField(default=0),
        ),
    ]
