# Generated by Django 2.2.4 on 2019-11-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0005_auto_20191126_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbllistanegra',
            name='producto',
            field=models.IntegerField(),
        ),
    ]
