# Generated by Django 2.2.4 on 2019-11-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0006_auto_20191126_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblapc',
            name='marca',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='tblapc',
            name='nombre',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='tblapc',
            name='tipo',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='tblapc',
            name='producto',
            field=models.IntegerField(),
        ),
    ]
