# Generated by Django 2.2.4 on 2019-11-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0007_auto_20191126_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblapc',
            name='ventas',
            field=models.IntegerField(default=0),
        ),
    ]
