# Generated by Django 2.2.4 on 2019-11-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0008_tblapc_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=30)),
                ('inversion', models.IntegerField()),
                ('ganacia', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tblSurtido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
