# Generated by Django 2.2.4 on 2019-11-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0009_tblbalances_tblsurtido'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.IntegerField()),
                ('pre', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='tblHistPrecios',
        ),
    ]
