# Generated by Django 2.2.4 on 2019-12-01 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0010_auto_20191127_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.AlterField(
            model_name='tblsurtido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualiaII.tblProducto'),
        ),
    ]
