# Generated by Django 2.2.4 on 2019-12-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0011_auto_20191201_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblproducto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
