# Generated by Django 2.2.4 on 2019-12-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0012_auto_20191201_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('tipo', models.IntegerField(default=2)),
            ],
        ),
    ]
