# Generated by Django 2.2.4 on 2019-12-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualiaII', '0013_tblusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblUsuario',
        ),
    ]
