# Generated by Django 2.2.4 on 2019-11-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nAgentes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaIngreso', models.DateField()),
                ('activo', models.BooleanField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PruebaAplicacion.Organizacion')),
            ],
        ),
    ]
